on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraping script
      run: |
        python main.py
    - name: Commit and push updated exports
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/events-*.*
        git commit -m "Update events dataset - $(date +'%Y-%m-%d')" || echo "No changes"
        git push
      continue-on-error: true  # in case no changes detected
